language: python
python:
  - "3.6"
  # - "2.7"
  # - "3.6-dev"
  # - "3.7"
install:
  - export ENVIRONMENT_YML="conda/environment.yml"
  - echo "ENVIRONMENT_YML = $ENVIRONMENT_YML"
  - echo "TRAVIS_PYTHON_VERSION = $TRAVIS_PYTHON_VERSION"
  - env
  - sudo apt-get update
  - sudo apt-get remove -y python-boto
  - sudo apt-get install -y libasound* build-essential gfortran libopenblas-dev liblapack-dev pandoc portaudio19-dev
  - if [[ "$TRAVIS_PYTHON_VERSION" == "2.7" ]]; then
      wget https://repo.continuum.io/miniconda/Miniconda2-latest-Linux-x86_64.sh -O miniconda.sh;
    else
      wget https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh;
    fi
  - bash miniconda.sh -b -p $HOME/miniconda
  - export PATH="$HOME/miniconda/bin:$PATH"
  - cp conda/.condarc ~/.condarc
  - conda update -n base conda
  - hash -r
  # - conda config --set always_yes yes --set changeps1 no
  # - conda config --add channels conda-forge
  - echo "running-- conda env create -f $ENVIRONMENT_YML -n testenv python=$TRAVIS_PYTHON_VERSION"
  - travis_wait 30 conda env create -q -f $ENVIRONMENT_YML -n testenv python=$TRAVIS_PYTHON_VERSION
  - source activate testenv
  - conda install pip
  - if [[ "$TRAVIS_PYTHON_VERSION" == "2.7" ]]; then
      pip install -U 'PyScaffold==2.5' ;
    else
      pip install -U PyScaffold ;
    fi
  # - sudo apt-get install -y python-boto
  - pip install -r requirements.txt
  - pip install -U -e .
  - python -c "import nltk; nltk.download('punkt')"
  - conda info -a
  - conda list
  - pip install codecov
  # - conda build conda-build-recipe
  # - conda install nlpia --use-local

after_success:
  - bash < (curl -s https://codecov.io/bash)
  - codecov

script:
  - python setup.py test
