language: python
python:
  - "2.7"
  - "3.6"
  # - "3.6-dev"
  # - "3.7"
install:
  - ENVIRONMENT_YML="conda/environment.yml"
  - sudo apt-get update
  - sudo apt-get install libasound* build-essential gfortran libopenblas-dev liblapack-dev pandoc portaudio19-dev
  - if [[ "$TRAVIS_PYTHON_VERSION" == "2.7" ]]; then
      wget https://repo.continuum.io/miniconda/Miniconda2-latest-Linux-x86_64.sh -O miniconda.sh;
    else
      wget https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh;
    fi
  - bash miniconda.sh -b -p $HOME/miniconda
  - export PATH="$HOME/miniconda/bin:$PATH"
  - hash -r
  - conda config --set always_yes yes --set changeps1 no
  - conda config --add channels conda-forge
  - conda info -a
  - echo "running-- conda env create -f $ENVIRONMENT_YML -n testenv python=$TRAVIS_PYTHON_VERSION"
  - travis_wait 30 conda env create -q -f $ENVIRONMENT_YML -n testenv python=$TRAVIS_PYTHON_VERSION
  - source activate testenv
  - conda install pip
  - if [[ "$TRAVIS_PYTHON_VERSION" == "2.7" ]]; then
      pip install 'PyScaffold==2.5' ;
      conda install boto ;
    else
      pip install PyScaffold ;
      conda install boto3 ;
    fi
  - pip install -r requirements/requirements-base.txt
  - python setup.py install
  # - conda build conda-build-recipe
  # - conda install nlpia --use-local


script:
  - python setup.py test
