name: nlpiaenv

channels:
  - conda-forge
  - defaults

dependencies:
  - boto3>=1.9.3,<1.10.0
  - gensim>=3.4.0,<3.5.0
  - jupyter>=1.0.0,<3.0.0
  - keras-applications>=1.0.4,<1.1.0
  - keras-preprocessing>=1.0.2,<1.1.0
  - keras>=2.2.2,<2.3.0
  - matplotlib>=2.2.2,<2.3.0
  - nltk>=3.2.5,<3.3.0
  - numpy>=1.15.1,<1.17.0
  - opencv>=3.3.0,<3.5.0
  - pandas
  - pandoc>=2.1.2,<2.2.0
  - pillow=4.3.0
  - plac>=0.9.6,<0.10.0
  - plotly>=3.1.1,<3.2.0
  - pyqt=5.6.0
  - python-levenshtein=0.12.0
  - redis-py>=2.10.6
  - spacy=2.0.12
  - swig=3.0.12
  - tensorflow=1.10.0

  - pip:
    - -r ../requirements/requirements-base.txt
