name: conda_env_nlpia

channels:
  - conda-forge
  - defaults

# - redis-py=2.10.6=py36h7a28c18_0

dependencies:
  - opencv=3.3.0
  - redis-py=2.10.6
  - matplotlib=2.1.0
  - pillow=4.3.0
  - pyqt=5.6.0
  - pytest=3.2.1
  - pip:
    - aiml>=0.8.6,<0.9.0
    - annoy>=1.9.5,<2.0.0
    - ChatterBot>=0.7.6,<0.8.0
    - cufflinks
    - django>=1.11.1,<1.12.0
    - future>=0.16.0
    - gensim>=2.1.0,<3.0.0
    - jupyter>=1.0.0,<2.0.0
    - Keras==2.0.8
    - lxml>=4.1.0,<4.2.0
    - matplotlib>=2.0.2
    - nltk>=3.2.2,<3.3.0
    - pandas-datareader>=0.5.0
    - pandas>=0.19.2
    - pip>=8.1.2
    - plotly>=2.3.0,<2.4.0
    - pugnlp>=0.0.12,<0.1.0
    - pypandoc>=1.4.0
    - python-Levenshtein>=0.12.0
    - scikit-learn>=0.18.1
    - scipy>=0.19.0
    - seaborn>=0.8
    - tensorflow>=1.3.0<2.0.0
    - tqdm>=4.11.2
    - tweepy>=3.5.0,<3.6.0
    - twython>=3.5.0,<3.6.0
    - wheel>=0.30.0a0
    - will>=2.1.0,<2.2.0

