name: nlpiaenv

channels:
  - conda-forge
  - defaults

dependencies:
  - opencv=3.3.0
  - redis-py>=2.10.6
  - matplotlib=2.2.2
  - pillow=4.3.0
  - pyqt=5.6.0
  - pytest=3.2.1
  - pandoc=2.1.2
  - spacy=2.0.9
  - swig>=3.0.12
  - nltk=3.2.5
  - gensim>=3.4.0
  - boto3
  - pip:
    - -r ../requirements-base.txt

